######################################################################
# Automatically generated by qmake (3.0) Sun Jan 18 18:25:12 2015
######################################################################

QT += gui core widgets
CONFIG += c++11
QMAKE_CXXFLAGS += -std=c99

TEMPLATE = app
TARGET = fanmaster
INCLUDEPATH += .

# Input
HEADERS += controller.h mainwindow.h ui_mainwindow.h
FORMS += mainwindow.ui
SOURCES += controller.cpp main.cpp mainwindow.cpp
